/* Table name: RECOMSYS */
DROP TABLE RECOMSYS;

CREATE TABLE RECOMSYS(
    RECOMNO       NUMBER(10)      NOT NULL,
    TRAVELNO    NUMBER(10)      NOT NULL, -- FK
    REGION      VARCHAR2(50)      NOT NULL,   
    CONTENT    CLOB    NOT NULL,
    FILE1    VARCHAR2(50)    NULL,
    FILE1_SAVED    VARCHAR2(50)    NULL,
    THUMB1    VARCHAR2(50)    NULL,
    
    FOREIGN KEY (TRAVELNO) REFERENCES TRAVEL (TRAVELNO),
    PRIMARY KEY (RECOMNO)
);

COMMENT ON TABLE RECOMSYS is '여행 추천 시스템';
COMMENT ON COLUMN RECOMSYS.RECOMNO is '추천 번호';
COMMENT ON COLUMN RECOMSYS.TRAVELNO is '여행지 번호';
COMMENT ON COLUMN RECOMSYS.REGION is '추천 여행지';
COMMENT ON COLUMN RECOMSYS.CONTENT is '추천 내용';
COMMENT ON COLUMN RECOMSYS.FILE1 is '메인이미지';
COMMENT ON COLUMN RECOMSYS.FILE1_SAVED is '실제 저장된 이미지';
COMMENT ON COLUMN RECOMSYS.THUMB1 is '메인이미지 thumb';


DROP SEQUENCE RECOMSYS_SEQ;

CREATE SEQUENCE RECOMSYS_SEQ
  START WITH 1              -- 시작 번호
  INCREMENT BY 1            -- 증가값
  MAXVALUE 99999            -- 최대값: 99999 --> NUMBER(5) 대응
  CACHE 2                   -- 2번은 메모리에서만 계산
  NOCYCLE;                  -- 다시 1부터 생성되는 것을 방지
